## Name: Reem Alyahya

# M4.Ex1: Housing Prices Model (PyCaret)

- Run: [**Open In Colab**](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W3/M6/exercises/ex1_pycaret_regression.ipynb)

## Exercise

Your task is to follow the steps outlined here, and apply them on the **California Housing Dataset** below:

- [**🚀 Regression**](https://pycaret.gitbook.io/docs/get-started/quickstart#regression)
    - Setup
    - Compare Models
    - Analyze Model
    - Predictions
    - Save the model

## California Housing Prices Dataset


Find and download the dataset from Kaggle at [California Housing Dataset](https://www.kaggle.com/datasets/dhirajnirne/california-housing-data).

According to [keras.io](https://keras.io/api/datasets/california_housing/):

> This dataset was obtained from the StatLib repository.
>
> It's a continuous regression dataset with 20,640 samples with 8 features each.
>
> The target variable is a scalar: the median house value for California districts, in dollars.
>
> The 8 input features are the following:
>
> - MedInc: median income in block group
> - HouseAge: median house age in block group
> - AveRooms: average number of rooms per household
> - AveBedrms: average number of bedrooms per household
> - Population: block group population
> - AveOccup: average number of household members
> - Latitude: block group latitude
> - Longitude: block group longitude
>
> This dataset was derived from the 1990 U.S. census, using one row per census block group. A block group is the smallest geographical unit for which the U.S. Census Bureau publishes sample data (a block group typically has a population of 600 to 3,000 people).
>
> A household is a group of people residing within a home. Since the average number of rooms and bedrooms in this dataset are provided per household, these columns may take surprisingly large values for block groups with few households and many empty houses, such as vacation resorts.

In [1]:
import pandas as pd
from autogluon import *
from autogluon.tabular import TabularPredictor
import os

In [2]:
os.environ['KMP_DUPLICATE_LIB_OK']='True'

### Load the data

In [3]:
from sklearn.model_selection import train_test_split
from autogluon.tabular import TabularDataset, TabularPredictor

# Load data
data = TabularDataset('data/housing.csv')

# Split 80% train, 20% test
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

**Task**: Your model should learn from this data and be able to predict the median housing price (`median_house_value`) in any district, given all the other metrics.

Please read the above dataset description to understand what the features mean.

## Step 1: Train

In [11]:

custom_hyperparameters = {
    'RF': {},   # Random Forest
    'CAT': {},  # CatBoost
    'XGB': {},  # XGBoost
    'FASTAI':{}, #NNFastAiTabularModel
    'NN_TORCH':{},
    # 'GBM': {}, # <-- Omit this to exclude LightGBM
}

predictor = TabularPredictor( label= 'median_house_value' ).fit(
    train_data,
    presets='medium_quality_faster_train',
    time_limit= 30,
    hyperparameters=custom_hyperparameters,
    included_model_types = ['FASTAI','NN_TORCH','RF','CAT','XGB'],
    num_cpus= 2,
    ag_args_fit ={'num_gpus' : 0}
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_075929"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.13
Operating System:   Darwin
Platform Machine:   x86_64
Platform Version:   Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:17 PDT 2025; root:xnu-11417.140.69~1/RELEASE_X86_64
CPU Count:          16
Memory Avail:       4.24 GB / 16.00 GB (26.5%)
Disk Space Avail:   777.73 GB / 931.55 GB (83.5%)
===================================================
Presets specified: ['medium_quality_faster_train']
Beginning AutoGluon training ... Time limit = 30s
AutoGluon will save models to "/Users/reemalyahya/Desktop/Bootcamp python/B5/student/C3/AutogluonModels/ag-20260422_075929"
Train Data Rows:    16512
Train Data Columns: 9
Label Column:       median_house_value
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (500001.0, 14999.0, 207194.69374, 115622.62645)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4343.99 MB
	Train Data (Original)  Memory Usage: 1.91 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
		('object', []) : 1 | ['ocean_proximity']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['ocean_proximity']
		('float', [])    : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
	0.1s = Fit runtime
	9 features in original data used to generate 9 features in processed data.
	Train Data (Processed) Memory Usage: 1.02 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 14860, Val Rows: 1652
User-specified model hyperparameters to be fit:
{
	'RF': [{}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'NN_TORCH': [{}],
}
Included models: ['FASTAI', 'NN_TORCH', 'RF', 'CAT', 'XGB'] (Specified by `included_model_types`, all other model types will be skipped)
Fitting 5 L1 models, fit_strategy="sequential" ...
Fitting model: RandomForest ... Training model for up to 29.89s of the 29.89s of remaining time.
	Fitting with cpus=2, gpus=0
	-50138.7767	 = Validation score   (-root_mean_squared_error)
	3.61s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 25.53s of the 25.53s of remaining time.
	Fitting with cpus=2, gpus=0
	Ran out of time, early stopping on iteration 4564.
	-43957.3719	 = Validation score   (-root_mean_squared_error)
	25.59s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 29.89s of the -0.10s of remaining time.
	Ensemble Weights: {'CatBoost': 0.88, 'RandomForest': 0.12}
	-43834.163	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 30.13s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 20567.6 rows/s (1652 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/reemalyahya/Desktop/Bootcamp python/B5/student/C3/AutogluonModels/ag-20260422_075929")

## Step 2: Describe and visualize

In [13]:
predictor.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-43834.162996,root_mean_squared_error,0.080321,29.210889,0.000431,0.007550,2,True,3
1,CatBoost,-43957.371891,root_mean_squared_error,0.006122,25.589222,0.006122,25.589222,1,True,2
2,RandomForest,-50138.776732,root_mean_squared_error,0.073768,3.614117,0.073768,3.614117,1,True,1

In [ ]:
predictor.fit_summary(show_plot=True, verbosity=2)

*** Summary of fit() ***
Estimated performance of each model:
                 model     score_val              eval_metric  pred_time_val   fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0  WeightedEnsemble_L2 -43522.165704  root_mean_squared_error       0.081915  59.182334                0.000431           0.007022            2       True          3
1             CatBoost -43704.936651  root_mean_squared_error       0.007072  55.656144                0.007072          55.656144            1       True          2
2         RandomForest -50138.776732  root_mean_squared_error       0.074412   3.519168                0.074412           3.519168            1       True          1
Number of models trained: 3
Types of models trained:
{'WeightedEnsembleModel', 'RFModel', 'CatBoostModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', []) : 1 | ['ocean_proximity']
('float', [])    : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
Plot summary of models saved to file: /Users/reemalyahya/Desktop/Bootcamp python/B5/student/C3/AutogluonModels/ag-20260422_075747/SummaryOfModels.html
*** End of fit() summary ***

{'model_types': {'RandomForest': 'RFModel',
  'CatBoost': 'CatBoostModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'RandomForest': -50138.77673166164,
  'CatBoost': -43704.93665140917,
  'WeightedEnsemble_L2': -43522.16570396911},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'RandomForest': ['RandomForest'],
  'CatBoost': ['CatBoost'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'RandomForest': 3.5191681385040283,
  'CatBoost': 55.6561439037323,
  'WeightedEnsemble_L2': 0.007021903991699219},
 'model_pred_times': {'RandomForest': 0.07441186904907227,
  'CatBoost': 0.007071971893310547,
  'WeightedEnsemble_L2': 0.00043129920959472656},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'model_hyperparams': {'RandomForest': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'random_state': 0,
   'bootstrap': True},
  'CatBoost': {'iterations': 10000,
   'learning_rate': 0.05,
   'random_seed': 0,
   'allow_writing_files': False,
   'eval_metric': 'RMSE'},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None}},
 'leaderboard':                  model     score_val              eval_metric  pred_time_val  \
 0  WeightedEnsemble_L2 -43522.165704  root_mean_squared_error       0.081915
 1             CatBoost -43704.936651  root_mean_squared_error       0.007072
 2         RandomForest -50138.776732  root_mean_squared_error       0.074412

     fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  \
 0  59.182334                0.000431           0.007022            2
 1  55.656144                0.007072          55.656144            1
 2   3.519168                0.074412           3.519168            1

    can_infer  fit_order
 0       True          3
 1       True          2
 2       True          1  }

In [14]:
predictor.feature_importance(test_data)

Computing feature importance via permutation shuffling for 9 features using 4128 rows with 5 shuffle sets...
	45.28s	= Expected runtime (9.06s per shuffle set)
	5.46s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
longitude,104993.653050,1374.850060,3.527371e-09,5,107824.488326,102162.817773
latitude,95291.259990,1447.599064,6.388936e-09,5,98271.886470,92310.633509
total_rooms,38173.643953,459.513554,2.519046e-09,5,39119.788711,37227.499195
median_income,32525.394029,622.845967,1.612877e-08,5,33807.842483,31242.945575
population,19374.233063,488.298314,4.837894e-08,5,20379.646039,18368.820086
ocean_proximity,11754.259935,200.822629,1.022072e-08,5,12167.756504,11340.763367
total_bedrooms,9543.501400,746.160529,4.447827e-06,5,11079.856241,8007.146558
households,7194.325800,457.444984,1.950917e-06,5,8136.211344,6252.440256
housing_median_age,4176.289845,381.971923,8.304547e-06,5,4962.775313,3389.804376