## Name: Reem Alyahya

# M4.Ex1: Housing Prices Model (PyCaret)

- Run: [**Open In Colab**](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W3/M6/exercises/ex1_pycaret_regression.ipynb)

## Exercise

Your task is to follow the steps outlined here, and apply them on the **California Housing Dataset** below:

- [**🚀 Regression**](https://pycaret.gitbook.io/docs/get-started/quickstart#regression)
    - Setup
    - Compare Models
    - Analyze Model
    - Predictions
    - Save the model

## California Housing Prices Dataset


Find and download the dataset from Kaggle at [California Housing Dataset](https://www.kaggle.com/datasets/dhirajnirne/california-housing-data).

According to [keras.io](https://keras.io/api/datasets/california_housing/):

> This dataset was obtained from the StatLib repository.
>
> It's a continuous regression dataset with 20,640 samples with 8 features each.
>
> The target variable is a scalar: the median house value for California districts, in dollars.
>
> The 8 input features are the following:
>
> - MedInc: median income in block group
> - HouseAge: median house age in block group
> - AveRooms: average number of rooms per household
> - AveBedrms: average number of bedrooms per household
> - Population: block group population
> - AveOccup: average number of household members
> - Latitude: block group latitude
> - Longitude: block group longitude
>
> This dataset was derived from the 1990 U.S. census, using one row per census block group. A block group is the smallest geographical unit for which the U.S. Census Bureau publishes sample data (a block group typically has a population of 600 to 3,000 people).
>
> A household is a group of people residing within a home. Since the average number of rooms and bedrooms in this dataset are provided per household, these columns may take surprisingly large values for block groups with few households and many empty houses, such as vacation resorts.

In [1]:
import pandas as pd
from autogluon import *
from autogluon.tabular import TabularPredictor
import os

In [2]:
os.environ['KMP_DUPLICATE_LIB_OK']='True'

### Load the data

In [3]:
from sklearn.model_selection import train_test_split
from autogluon.tabular import TabularDataset, TabularPredictor

# Load data
data = TabularDataset('data/housing.csv')

# Split 80% train, 20% test
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

**Task**: Your model should learn from this data and be able to predict the median housing price (`median_house_value`) in any district, given all the other metrics.

Please read the above dataset description to understand what the features mean.

## Step 1: Train

In [4]:

custom_hyperparameters = {
    'RF': {},   # Random Forest
    'CAT': {},  # CatBoost
    'XGB': {},  # XGBoost
    'FASTAI':{}, #NNFastAiTabularModel
    'NN_TORCH':{},
    # 'GBM': {}, # <-- Omit this to exclude LightGBM
}

predictor = TabularPredictor( label= 'median_house_value' ).fit(
    train_data,
    presets='medium_quality_faster_train',
    time_limit= 60,
    hyperparameters=custom_hyperparameters,
    included_model_types = ['FASTAI','NN_TORCH','RF','CAT','XGB'],
    num_cpus= 2,
    ag_args_fit ={'num_gpus' : 0}
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_082146"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.13
Operating System:   Darwin
Platform Machine:   x86_64
Platform Version:   Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:17 PDT 2025; root:xnu-11417.140.69~1/RELEASE_X86_64
CPU Count:          16
Memory Avail:       4.65 GB / 16.00 GB (29.1%)
Disk Space Avail:   775.51 GB / 931.55 GB (83.2%)
===================================================
Presets specified: ['medium_quality_faster_train']
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/reemalyahya/Desktop/Bootcamp python/B5/student/C3/AutogluonModels/ag-20260422_082146"
Train Data Rows:    16512
Train Data Columns: 9
Label Column:       median_house_value
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (500001.0, 14999.0, 207194.69374, 115622.62645)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4726.83 MB
	Train Data (Original)  Memory Usage: 1.91 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
		('object', []) : 1 | ['ocean_proximity']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['ocean_proximity']
		('float', [])    : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
	0.1s = Fit runtime
	9 features in original data used to generate 9 features in processed data.
	Train Data (Processed) Memory Usage: 1.02 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 14860, Val Rows: 1652
User-specified model hyperparameters to be fit:
{
	'RF': [{}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'NN_TORCH': [{}],
}
Included models: ['FASTAI', 'NN_TORCH', 'RF', 'CAT', 'XGB'] (Specified by `included_model_types`, all other model types will be skipped)
Fitting 5 L1 models, fit_strategy="sequential" ...
Fitting model: RandomForest ... Training model for up to 59.89s of the 59.89s of remaining time.
	Fitting with cpus=2, gpus=0
	-50138.7767	 = Validation score   (-root_mean_squared_error)
	5.34s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 53.81s of the 53.81s of remaining time.
	Fitting with cpus=2, gpus=0
	Ran out of time, early stopping on iteration 8078.
	-43715.454	 = Validation score   (-root_mean_squared_error)
	53.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.89s of the -0.16s of remaining time.
	Ensemble Weights: {'CatBoost': 0.864, 'RandomForest': 0.136}
	-43536.5475	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 60.2s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 19794.4 rows/s (1652 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/reemalyahya/Desktop/Bootcamp python/B5/student/C3/AutogluonModels/ag-20260422_082146")

## Step 2: Describe and visualize

In [5]:
predictor.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-43536.547536,root_mean_squared_error,0.083458,59.265831,0.001406,0.008805,2,True,3
1,CatBoost,-43715.454018,root_mean_squared_error,0.007260,53.919764,0.007260,53.919764,1,True,2
2,RandomForest,-50138.776732,root_mean_squared_error,0.074792,5.337262,0.074792,5.337262,1,True,1

In [6]:
predictor.fit_summary(show_plot=True, verbosity=2)

*** Summary of fit() ***
Estimated performance of each model:
                 model     score_val              eval_metric  pred_time_val   fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0  WeightedEnsemble_L2 -43536.547536  root_mean_squared_error       0.083458  59.265831                0.001406           0.008805            2       True          3
1             CatBoost -43715.454018  root_mean_squared_error       0.007260  53.919764                0.007260          53.919764            1       True          2
2         RandomForest -50138.776732  root_mean_squared_error       0.074792   5.337262                0.074792           5.337262            1       True          1
Number of models trained: 3
Types of models trained:
{'CatBoostModel', 'RFModel', 'WeightedEnsembleModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', []) : 1 | ['ocean_proximity']
('float', [])    : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
Plot summary of models saved to file: /Users/reemalyahya/Desktop/Bootcamp python/B5/student/C3/AutogluonModels/ag-20260422_082146/SummaryOfModels.html
*** End of fit() summary ***

{'model_types': {'RandomForest': 'RFModel',
  'CatBoost': 'CatBoostModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'RandomForest': -50138.77673166164,
  'CatBoost': -43715.45401792398,
  'WeightedEnsemble_L2': -43536.54753648427},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'RandomForest': ['RandomForest'],
  'CatBoost': ['CatBoost'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'RandomForest': 5.33726167678833,
  'CatBoost': 53.919764041900635,
  'WeightedEnsemble_L2': 0.008805274963378906},
 'model_pred_times': {'RandomForest': 0.07479190826416016,
  'CatBoost': 0.00726008415222168,
  'WeightedEnsemble_L2': 0.001405954360961914},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'model_hyperparams': {'RandomForest': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'random_state': 0,
   'bootstrap': True},
  'CatBoost': {'iterations': 10000,
   'learning_rate': 0.05,
   'random_seed': 0,
   'allow_writing_files': False,
   'eval_metric': 'RMSE'},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None}},
 'leaderboard':                  model     score_val              eval_metric  pred_time_val  \
 0  WeightedEnsemble_L2 -43536.547536  root_mean_squared_error       0.083458
 1             CatBoost -43715.454018  root_mean_squared_error       0.007260
 2         RandomForest -50138.776732  root_mean_squared_error       0.074792

     fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  \
 0  59.265831                0.001406           0.008805            2
 1  53.919764                0.007260          53.919764            1
 2   5.337262                0.074792           5.337262            1

    can_infer  fit_order
 0       True          3
 1       True          2
 2       True          1  }

In [7]:
predictor.feature_importance(test_data)

Computing feature importance via permutation shuffling for 9 features using 4128 rows with 5 shuffle sets...
	44.89s	= Expected runtime (8.98s per shuffle set)
	6.22s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
longitude,108464.782729,1422.306607,3.547314e-09,5,111393.331690,105536.233767
latitude,98686.417885,1502.286701,6.442120e-09,5,101779.646967,95593.188804
total_rooms,42824.709176,552.698877,3.328599e-09,5,43962.723803,41686.694550
median_income,29067.208164,545.315489,1.485783e-08,5,30190.020292,27944.396036
population,18476.011544,527.089949,7.939921e-08,5,19561.297035,17390.726053
total_bedrooms,12545.476622,960.609749,4.092919e-06,5,14523.385372,10567.567872
ocean_proximity,10646.207425,200.993699,1.523789e-08,5,11060.056230,10232.358620
households,7934.372557,469.622598,1.465889e-06,5,8901.331978,6967.413137
housing_median_age,3853.939169,417.302708,1.624081e-05,5,4713.171212,2994.707125

## Step 3: Predict and evaluate

In [8]:
predictor.predict(test_data)

20046    273650.250000
3024     342729.625000
15663    732918.625000
20484    496266.718750
9814     456452.781250
             ...
15362    227969.703125
16623    224554.234375
18086    493064.687500
2144      69529.367188
3665     173521.703125
Name: median_house_value, Length: 4128, dtype: float32

In [9]:
predictor.evaluate(test_data)

{'root_mean_squared_error': -61791.3005760912,
 'mean_squared_error': -3818164826.884848,
 'mean_absolute_error': -36319.906869814375,
 'r2': 0.7086280016174513,
 'pearsonr': 0.8559938956878151,
 'median_absolute_error': -18783.671875}

In [10]:
models = predictor.model_names()

## Step 4: deployment

In [23]:
predictor = TabularPredictor.load('AutogluonModels/ag-20260422_082146')

In [24]:
predictor.persist()

Persisting 3 models in memory. Models will require 7.74% of memory.

['WeightedEnsemble_L2', 'RandomForest', 'CatBoost']

In [25]:
predictor.clone_for_deployment(path='ag-20260422_082146')

Cloned TabularPredictor located in '/Users/reemalyahya/Desktop/Bootcamp python/B5/student/C3/AutogluonModels/ag-20260422_082146' to 'ag-20260422_082146'.
	To load the cloned predictor: predictor_clone = TabularPredictor.load(path="ag-20260422_082146")
Clone: Keeping minimum set of models required to predict with best model 'WeightedEnsemble_L2'...
Clone: Removing artifacts unnecessary for prediction. NOTE: Clone can no longer fit new models, and most functionality except for predict and predict_proba will no longer work

'/Users/reemalyahya/Desktop/Bootcamp python/B5/student/C3/ag-20260422_082146'

In [30]:
predictor_opt = TabularPredictor.load('ag-20260422_082146')
predictor_opt.persist()
predictions = predictor_opt.predict(test_data)

Persisting 3 models in memory. Models will require 7.33% of memory.