## Name: Reem Alyahya

# M1.Ex4: Modeling Non-linear Patterns

- Run: [**Open In Colab**](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W3/M1/exercises/ex4_non-linear.ipynb)
- Raw Dataset: [bmi_and_life_expectancy.csv](https://raw.githubusercontent.com/HassanAlgoz/B5/main/content/datasets/bmi_and_life_expectancy.csv)

In [1]:
import pandas as pd
import sklearn

### Step 1. Load the data

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/HassanAlgoz/B5/main/content/datasets/bmi_and_life_expectancy.csv")
df.head()

       Country  Life expectancy       BMI
0  Afghanistan             52.8  20.62058
1      Albania             76.8  26.44657
2      Algeria             75.5  24.59620
3      Andorra             84.6  27.63048
4       Angola             56.7  22.25083

### Step 2.a Assign variables `X` to the features and `y` to the target

In [4]:
x = df[['Country', 'Life expectancy']]
y = df['BMI']

### Step 2.b print the type of each

In [5]:
x.dtypes, y.dtype

(Country                str
 Life expectancy    float64
 dtype: object,
 dtype('float64'))

### Step 2.c identify whether the target is categorical or numerical & whether the task is regression or classification

- Numerical
- Regression

### Step 3. Identify the number of samples and columns of both the data matrix and the target

In [6]:
x.shape, y.shape

((163, 2), (163,))

### Step 4. Summarize the distribution of the data (min, max, median, mean, and standard deviation)

In [10]:
x.select_dtypes(include='number').agg(['min', 'max', 'median', 'mean', 'std'])

        Life expectancy
min           44.500000
max           84.600000
median        71.800000
mean          69.666933
std            8.981933

### Step 5. Plot the feature vs the target

### Step 6. What is the relationship between the feature and the target? (increasing or decreasing or none)

### Step 7. Make two modeling techniques

First model is just a Linear Regression model: `from sklearn.linear_model import LinearRegression`

Second model: Use one of the previously mentioned methods to model a non-linear relationship

1. `from sklearn.tree import DecisionTreeRegressor`
2. or `from sklearn.preprocessing import PolynomialFeatures`

### Step 8. Split the dataset into train and test sets

### Step 9. Train both models on the training set

### Step 10. Evaluate and compare which of the two models score better on the `train` set

### Step 11. Evaluate and compare which of the two models score better on the `test` set