## Name: Reem Alyahya

# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [3]:
series_1 = pd.Series(np.random.randint(1,5, size = 100))
series_2 = pd.Series(np.random.randint(1,4, size = 100))
series_3 = pd.Series(np.random.randint(10000,30001, size = 100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [12]:
df = pd.DataFrame(pd.concat([series_1, series_2, series_3], axis=1))
df

    0  1      2
0   2  3  12105
1   4  2  10226
2   3  1  16621
3   4  2  25646
4   2  3  13037
.. .. ..    ...
95  1  2  14751
96  1  3  24053
97  1  1  11096
98  2  1  24571
99  2  1  20468

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [17]:
df.columns =['bedrs', 'bathrs', 'price_sqr_meter']
df.head(10)

   bedrs  bathrs  price_sqr_meter
0      2       3            12105
1      4       2            10226
2      3       1            16621
3      4       2            25646
4      2       3            13037
5      1       2            16556
6      4       2            15236
7      2       1            28063
8      4       1            17939
9      1       1            11958

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [19]:
bigcolum = pd.concat([df['bedrs'], df['bathrs'], df['price_sqr_meter']], axis=0)
bigcolum = pd.DataFrame(bigcolum)

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [20]:
bigcolum.index

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=300)

### Step 7. Reindex the DataFrame so it goes from 0 to 299